apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
spec:
  selector:
    app: {{ .Chart.Name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      nodePort: {{ .Values.app.service.nodePort }}
  type: {{ .Values.app.service.type }}
