apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mysql
spec:
  selector:
    app: {{ .Chart.Name }}-mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
  clusterIP: None  # Headless service to support stateful apps
