# templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: {{ .Values.todoApp.service.port }}
      targetPort: {{ .Values.todoApp.containerPort }}
  type: {{ .Values.todoApp.service.type }}