# templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: {{ .Values.todoApp.replicas }}
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: {{ .Values.todoApp.image }}
          ports:
            - containerPort: {{ .Values.todoApp.containerPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db:{{ .Values.mysql.service.port }}/{{ .Values.mysql.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"