---
# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_DATABASE
              value: "tododb"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mysql-init-script
          configMap:
            name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Headless service for internal communication