# templates/app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.app.springDatasourceUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.app.springDatasourceUsername | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.app.springDatasourcePassword | quote }}
          ports:
            - containerPort: {{ .Values.app.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.nodePort }}
  selector:
    app: todo-app